services:
  - type: web
    name: order-sorter
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DATABASE_URL
        value: postgresql://order_db_ms9k_user:M5O2g5kYzdbOimRmpFn2AjH6HUInt82j@dpg-d7ie25jeo5us73dfti4g-a/order_db_ms9k
